Update requirements.txt
Running gorilla_falcon_cli.py withou einops package returns the following error:

ImportError: This modeling file requires the following packages that were not found in your environment: einops. Run `pip install einops`